### ISSUE TITLE
Behavior of registeredSensorsChangeInfo

### ISSUE THREAD

**Issue by bnouhanna** [coatyio/coaty-js#12]
**Describe the bug**
I created a SensorThingsController that extends SensorSourceController with a fixed uuid (based on the coaty-examples sensor-things). I am trying to detect when the sensor is online or offline, so I use 
`this.registeredSensorsChangeInfo$.subscribe(changeInfo => {}`
The issues am facing are:
-  the `changeInfo.added.forEach( sensor =>` doesn't work the third time the sensor is online
- the `changeInfo.changed.forEach( sensor =>`  and `changeInfo.total.forEach( sensor =>` is triggered three times once the sensor is online for the third time
-  the `changeInfo.removed.forEach( sensor =>`  only works when the sensor is switched off the first time. 
any explanation for such behavior.

**Expected behavior**
I expect the `changeInfo.removed.forEach( sensor =>` to be triggered whenever the sensor is offline. 
I expect the `changeInfo.added.forEach( sensor =>` to be triggered whenever the sensor is online. 
I expect the `changeInfo.changed.forEach( sensor =>` to not be triggered three times when the sensor is online for the third time.

**To Reproduce**
1. create a  `SensorSourceController`
2. create a `ThingSensorObservationObserverController` and use `this.registeredSensorsChangeInfo$.subscribe`
3. switch the `SensorSourceController` on/off multiple times and check the behavior of the  `this.registeredSensorsChangeInfo$.subscribe`

**Comment by ffa500** [comment]
Can you please provide us with a minimal runnable Coaty project with two Coaty agents that expose the described behavior. Please put it on a public site for downloading or send it as a zipped attachment to our [Coaty Team Email Address](mailto:coaty.team@gmail.com). Thanks for your support!

**Comment by bnouhanna** [comment]
## Update of the issue, based on the review I received (for future reference) 
The issue arises from the fact, that I didn't add the Things parentObjectId property in the initial
Things definition BEFORE the Thing is advertised! and I defined it AFTER the Thing is advertised. The
parentObjectId information is crucial for lifecycle management on the remote service agent side. Only if
the parentObjectId is set to the objectId of the publishing sensor agent, the service agent can track
online/offline state of this Thing object (and its sensors) properly. Therefore, the Thing definition should be:
`this._thing = {
name: "Temperature",
objectId: this.runtime.newUuid(),
objectType: SensorThingsTypes.OBJECT_TYPE_THING,
parentObjectId: this.container.identity.objectId,
coreType: "CoatyObject",
description: "A device that can measure the temperature values",
};`
