### ISSUE TITLE
Custom DB Adapter for Neo4j?

### ISSUE THREAD

**Issue by erkankarabulut** [coatyio/coaty-js#23]
**This is neither a bug nor a feature request.** 
According to "[Implement a custom database adapter](https://coatyio.github.io/coaty-js/man/developer-guide/#implement-a-custom-database-adapter)" part of the documentation, new custom db adapter should derive from `DbAdapterBase` and implement `IDbAdapter` and `IDbAdapterExtension` interfaces.

Passing [neo4-driver](https://www.npmjs.com/package/neo4j-driver) as adapter inside configuration seems like a fuzzy idea. Because it's not clear what to send as `connectionString` and `connectionOptions`.

```
export function serviceConfig(agentInfo: AgentInfo, agentName: string): Configuration {
    return {
        ....
        databases: {
            neo4j: {
                adapter: "Neo4jAdapter",
                connectionString: "?",
                connectionOptions: "?"
            }
        },
    };
}

DbAdapterFactory.registerAdapter("Neo4jAdapter", neo4j-driver);
```
Neo4j-driver provides only 1 method to run any type of query, e.g. create, delete, update, get objects. So I assume the methods that are provided by `IDbAdapter` and `IDbAdapterExtension` interfaces should be implemented manually. But there is no example implementation in the documentation.

```
export class Neo4jAdapter extends DbAdapterBase implements IDbAdapter, IDbAdapterExtension {
...
```

**Q**: Are these explanations/assumptions are correct and what methods supposed to be implemented inside this custom db adapter?

**Comment by ffa500** [comment]
Thanks for your interest in Coaty's Unified Storage API. In general, implementing a custom DB adapter is a considerable undertaking and can be achieved easiest by taking the implementation of the predefined [Postgres adapter](https://github.com/coatyio/coaty-js/blob/master/src/db/adapter-postgres/postgres-adapter.ts) or one of the other adapters included in Coaty JS as an example or template.

You should not confuse the notion of a Coaty DB adapter and a concrete DB driver, such as neo4-driver. You cannot pass such a driver instance on adapter registration! You have to implement a custom DbAdapter class that derives from DbAdapterBase. Inside this class you can implement the functionality of the two interfaces as specified. Note that you are free to choose to realize only Sql or NoSql and/or extension interfaces depending on what your DB driver supports and what you require in your Coaty application. 

**Inside** your adapter class you create and hold a reference to your neo4j-driver like this:

```ts
class Neo4jAdapter extends DbAdapterBase {
    private _driver;

   // somewhere in your class code, maybe in the ctor, you need to setup the driver like this.
   // If needed, you can take required options like  'neo4j://localhost' and basic auth (username, password)
   // from the adapterOptions, connectionString and connectionOptions
   // as specified in the Coaty adapter configuration. You can access these within your adapter class
   // as follows:
   constructor(connectionInfo: DbConnectionInfo) {
        super(connectionInfo);
        this._driver = neo4j.driver(
           this.connectionInfo.connectionString,      // 'neo4j://localhost',
           neo4j.auth.basic(this.connectionInfo.connectionOptions.username, this.connectionInfo.connectionOptions.password));
   }
}
```

In the adapter configuration you specify the options as follows:

```ts
databases: {
            neo4j: {
                adapter: "Registered_name_for_my_Neo4jAdapter",
                adapterOptions: { ... },   // if required
                connectionString:  'neo4j://localhost',
                connectionOptions: {
                     username: "foo",
                     password: "123456"
                }
            }
        },
```

You may also specify **adapter options** that you can pass to neo4jdriver if required. These options concern the adapter and the neo4jdriver as a whole, not related to a specific connection.

Note that adapterOptions, connectionString and connectionOptions are **optional** (see interface [DbConnectionInfo](https://github.com/coatyio/coaty-js/blob/master/src/runtime/configuration.ts)), so you
don't need to pass them in the adapter configuration if you **don't** require them in Neo4j:

```ts
databases: {
            neo4j: {
                adapter: "Registered_name_for_my_Neo4jAdapter",
            }
        },
```


Next, you need to register your custom adapter class **before** using it in Coaty:

```ts
import { Neo4jAdapter } from "my-package-with-neo4j-adapter";

...

DbAdapterFactory.registerAdapter("Registered_name_for_my_Neo4jAdapter", Neo4jAdapter);
```

Registring means that you register the new adapter **class type** with a unique string for this type that can be chosen arbitrarily **but** must be equal to the name of the adapter as specified in the neo4j DB configuration. You do **not** register the adapter by specifying the neo4j driver here!

Finally, to use your custom adapter, you create a `DbContext` for applying operations on it by referencing the registered configuration:

```ts
const dbContext = new DbContext(configuration.databases["Registered_name_for_my_Neo4jAdapter"]);

dbContext.addCollection("mycollection");
```

**Comment by erkankarabulut** [comment]
Thank you for your detailed reply! Now I am able to implement a neo4j adapter with some basic functionalities.

**Comment by ffa500** [comment]
One general remark regarding use of Coaty DB adapters to realize a Neo4J or other graph-database integration: The Coaty Query Language is just designed to support SQL and NO-SQL databases to query and retrieve Coaty (i.e. JSON) objects. It doesn't directly support relationship-based queries in the way they are offered by special graph query languages, like Cypher, GraphQL, etc. 

However, you can easily enable Coaty agents to query such relationships across a Coaty application: Use the Call-Return pattern with a specific operation ID like "neo4j-query" and pass the Neo4j Cypher query as a string argument to the Call event. On the database side, observe this Call pattern, extract the Cypher query from an incoming Call event and pass it to the Neo4J JS driver directly. The driver's result is passed to the Return event which is sent back to the caller. This approach bypasses Coaty's Universal Storage API but leverages Coaty's remote operation feature to handle any specific (qraph) query language.
